# Generated by Django 5.2.9 on 2025-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
