# Generated by Django 5.2.9 on 2025-12-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_borrow_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date']},
        ),
    ]
