# Generated by Django 6.0 on 2026-01-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_action_a_type_payment_purchased_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_success',
        ),
        migrations.AddField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.book'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('borrow', 'Borrow'), ('reserve', 'Reserve'), ('purchase', 'Purchase')], max_length=20, null=True),
        ),
    ]
