# Generated by Django 6.0 on 2026-01-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_payment_is_success_payment_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
